USE [master]
GO

/****** Object:  Database [Arduino]    Script Date: 22.12.2017 00:12:09 ******/
CREATE DATABASE [Arduino]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Arduino', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Arduino.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Arduino_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Arduino_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Arduino] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Arduino].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Arduino] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Arduino] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Arduino] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Arduino] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Arduino] SET ARITHABORT OFF 
GO

ALTER DATABASE [Arduino] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Arduino] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Arduino] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Arduino] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Arduino] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Arduino] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Arduino] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Arduino] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Arduino] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Arduino] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Arduino] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Arduino] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Arduino] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Arduino] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Arduino] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Arduino] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Arduino] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Arduino] SET RECOVERY FULL 
GO

ALTER DATABASE [Arduino] SET  MULTI_USER 
GO

ALTER DATABASE [Arduino] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Arduino] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Arduino] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Arduino] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Arduino] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Arduino] SET  READ_WRITE 
GO

